[tool.poetry]
name = "forgery"
version = "0.1.0"
description = ""
authors = ["desmitry <desmitry@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12.3"
playwright = "^1.43.0"
loguru = "^0.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
